//! Regenerate `src/generated.rs` from a Lucide release.
//!
//! ```sh
//! npm pack lucide-static && tar xzf lucide-static-*.tgz
//! cargo run -p next-rust-icons --example generate -- package
//! cargo fmt -p next-rust-icons
//! ```
//!
//! `icon-nodes.json` maps each icon name to its SVG elements:
//! `{"house": [["path", {"d": "…"}], …]}`. Files in `icons/` without an entry
//! there are former names (`home` for `house`); they become aliases of the
//! icon with the same drawing.

use std::collections::BTreeMap;
use std::fmt::Write;

/// One SVG element: tag and attributes.
type Element = (String, BTreeMap<String, serde_json::Value>);

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let [dir] = args.as_slice() else {
        eprintln!("usage: generate <lucide-static package directory>");
        std::process::exit(2);
    };
    let dir = std::path::Path::new(dir);
    let read = |file: &str| std::fs::read_to_string(dir.join(file)).unwrap_or_else(|e| panic!("read {file}: {e}"));
    let nodes: BTreeMap<String, Vec<Element>> =
        serde_json::from_str(&read("icon-nodes.json")).expect("icon-nodes.json");
    let package: serde_json::Value = serde_json::from_str(&read("package.json")).expect("package.json");
    let version = package["version"].as_str().expect("version");

    let mut out = String::new();
    writeln!(
        out,
        "// @generated by `cargo run -p next-rust-icons --example generate` from Lucide {version}. Do not edit.\n\
         // Icon artwork: Lucide, ISC license (see LICENSE-LUCIDE).\n\n\
         use crate::{{Icon, IconData}};\n\n\
         pub(crate) const LUCIDE_VERSION: &str = {version:?};\n"
    )
    .unwrap();

    let mut seen = BTreeMap::new();
    let mut statics = String::new();
    let mut all = String::new();
    let mut by_body = BTreeMap::new();
    for (name, elements) in &nodes {
        let body = body(elements);
        by_body.insert(body.clone(), name.clone());
        let func = pascal(name);
        if let Some(other) = seen.insert(func.clone(), name.clone()) {
            panic!("`{name}` and `{other}` both become `{func}`");
        }
        let constant = name.to_uppercase().replace('-', "_");
        writeln!(statics, "    pub static {constant}: IconData = IconData {{ name: {name:?}, body: {body:?} }};")
            .unwrap();
        writeln!(all, "    &data::{constant},").unwrap();
        writeln!(
            out,
            "/// ![{name}](data:image/svg+xml;base64,{preview}) [`{name}`](https://lucide.dev/icons/{name})\n\
             pub fn {func}() -> Icon {{\n    Icon::new(&data::{constant})\n}}\n",
            preview = base64(&preview(&body)),
        )
        .unwrap();
    }
    // Former names, matched to their icon by drawing.
    let mut aliases = BTreeMap::new();
    for entry in std::fs::read_dir(dir.join("icons")).expect("icons directory") {
        let path = entry.expect("icons entry").path();
        let Some(name) = path.file_name().and_then(|n| n.to_str()).and_then(|n| n.strip_suffix(".svg")) else {
            continue;
        };
        if nodes.contains_key(name) {
            continue;
        }
        let drawing = body(&parse_svg(&std::fs::read_to_string(&path).expect("read svg")));
        let target = by_body.get(&drawing).unwrap_or_else(|| panic!("alias {name}: no icon has its drawing"));
        aliases.insert(name.to_owned(), target.clone());
    }
    let mut alias_table = String::new();
    for (alias, target) in &aliases {
        let func = pascal(alias);
        let target_fn = pascal(target);
        let constant = target.to_uppercase().replace('-', "_");
        writeln!(alias_table, "    ({alias:?}, &data::{constant}),").unwrap();
        match seen.get(&func) {
            // `arrow-down-01` for `arrow-down-0-1`: the function already exists.
            Some(existing) if existing == target => continue,
            Some(other) => panic!("`{alias}` and `{other}` both become `{func}`"),
            None => {
                seen.insert(func.clone(), alias.clone());
            }
        }
        writeln!(
            out,
            "/// Former name of [`{target_fn}`] (`{alias}`).\npub fn {func}() -> Icon {{\n    {target_fn}()\n}}\n"
        )
        .unwrap();
    }
    writeln!(out, "/// Every icon, sorted by name.\npub(crate) static ALL: &[&IconData] = &[\n{all}];\n").unwrap();
    writeln!(out, "/// Former names and their icons, sorted.\npub(crate) static ALIASES: &[(&str, &IconData)] = &[\n{alias_table}];\n")
        .unwrap();
    writeln!(out, "/// The drawings.\npub mod data {{\n    use crate::IconData;\n\n{statics}}}").unwrap();

    let dest = concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated.rs");
    std::fs::write(dest, out).expect("write src/generated.rs");
    println!("wrote {} icons and {} former names from Lucide {version} to {dest}", nodes.len(), aliases.len());
}

/// `arrow-down-0-1` → `ArrowDown01`, as lucide-react names them.
fn pascal(name: &str) -> String {
    name.split('-')
        .map(|part| {
            let mut chars = part.chars();
            chars.next().map(|c| c.to_ascii_uppercase().to_string() + chars.as_str()).unwrap_or_default()
        })
        .collect()
}

/// The elements of a Lucide SVG file (self-closing children of `<svg>`).
fn parse_svg(svg: &str) -> Vec<Element> {
    let start = svg.find("<svg").expect("<svg");
    let inner = &svg[start + svg[start..].find('>').expect(">") + 1..svg.rfind("</svg>").expect("</svg>")];
    let mut elements = Vec::new();
    for part in inner.split('<').skip(1) {
        let part = part.trim_end().trim_end_matches('>').trim_end().trim_end_matches('/');
        let (tag, mut rest) = part.split_once(char::is_whitespace).unwrap_or((part, ""));
        let mut attrs = BTreeMap::new();
        while let Some(eq) = rest.find("=\"") {
            let key = rest[..eq].trim();
            let value_end = rest[eq + 2..].find('"').expect("closing quote");
            attrs.insert(key.to_owned(), serde_json::Value::String(rest[eq + 2..eq + 2 + value_end].to_owned()));
            rest = &rest[eq + 2 + value_end + 1..];
        }
        elements.push((tag.to_owned(), attrs));
    }
    elements
}

/// The elements as SVG markup: `<path d="…"/><circle cx="12" …/>`.
fn body(elements: &[Element]) -> String {
    let mut out = String::new();
    for (tag, attrs) in elements {
        assert!(tag.bytes().all(|b| b.is_ascii_lowercase()), "unexpected element {tag}");
        out.push('<');
        out.push_str(tag);
        for (key, value) in attrs {
            assert!(key.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'-'), "unexpected attribute {key}");
            let value = match value {
                serde_json::Value::String(s) => s.clone(),
                other => other.to_string(),
            };
            let value = value.replace('&', "&amp;").replace('"', "&quot;").replace('<', "&lt;");
            write!(out, " {key}=\"{value}\"").unwrap();
        }
        out.push_str("/>");
    }
    out
}

/// The icon as a standalone image for documentation hovers: black lines on
/// a white tile, readable in light and dark editors.
fn preview(body: &str) -> String {
    format!(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#000\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect width=\"24\" height=\"24\" fill=\"#fff\" stroke=\"none\" rx=\"2\"/>{body}</svg>"
    )
}

fn base64(input: &str) -> String {
    const B64: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let bytes = input.as_bytes();
    let mut out = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let n = chunk.iter().enumerate().fold(0u32, |acc, (i, &b)| acc | (u32::from(b) << (16 - 8 * i)));
        for i in 0..4 {
            out.push(if i <= chunk.len() { B64[((n >> (18 - 6 * i)) & 63) as usize] as char } else { '=' });
        }
    }
    out
}
