//! Project and file templates.

/// Where a new project gets the framework from.
pub enum FrameworkSource {
    /// A local checkout (`--framework-path`).
    Path(String),
    /// crates.io, pinned to this CLI's version.
    Registry,
    /// The GitHub repository's default branch.
    Git,
}

impl FrameworkSource {
    /// Human-readable description for terminal output.
    pub fn describe(&self) -> String {
        match self {
            FrameworkSource::Path(p) => format!("local checkout · {p}"),
            FrameworkSource::Registry => format!("crates.io · next-rust {}", env!("CARGO_PKG_VERSION")),
            FrameworkSource::Git => crate::REPO_URL.trim_start_matches("https://").to_owned(),
        }
    }
}

/// Version requirement for crates.io apps: `major.minor` of this CLI, so
/// `cargo update` picks up every automatic patch release (0.0.1, 0.0.2, …).
fn registry_requirement() -> String {
    let v = env!("CARGO_PKG_VERSION");
    v.splitn(3, '.').take(2).collect::<Vec<_>>().join(".")
}

pub fn cargo_toml(name: &str, source: &FrameworkSource) -> String {
    let (dep, build_dep) = match source {
        FrameworkSource::Path(p) => (
            format!("{{ path = \"{}/crates/next-rust\" }}", p.trim_end_matches('/')),
            format!("{{ path = \"{}/crates/next-rust-build\" }}", p.trim_end_matches('/')),
        ),
        FrameworkSource::Registry => {
            (format!("\"{}\"", registry_requirement()), format!("\"{}\"", registry_requirement()))
        }
        FrameworkSource::Git => {
            (format!("{{ git = \"{}\" }}", crate::REPO_URL), format!("{{ git = \"{}\" }}", crate::REPO_URL))
        }
    };
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
next-rust = {dep}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"

[build-dependencies]
next-rust-build = {build_dep}

# Production builds. `next-rust build` always uses these settings (see
# [build] in next-rust.toml); they also apply to a plain `cargo build --release`.
[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = true
"#
    )
}

pub const BUILD_RS: &str = "fn main() {\n    next_rust_build::generate();\n}\n";

pub const CONFIG: &str = r#"# Next Rust configuration. Every setting is optional.

[app]
directory = "app"
# public = "public"

[server]
port = 3000

# [rendering]
# default = "auto"     # auto | static | dynamic
# streaming = true
"#;

pub const GITIGNORE: &str = "/target\n/.next-rust\n.env*.local\n";

pub const ENV_EXAMPLE: &str = "# Server-only secrets (never sent to the browser)\nDATABASE_URL=postgres://localhost/app\n\n# Values safe for client code must use the public prefix\nNEXT_RUST_PUBLIC_SITE_NAME=My App\n";

pub const API_RS: &str = r#"use next_rust::prelude::*;

pub async fn GET(req: Request) -> Response {
    let name = req.query_param("name").unwrap_or_else(|| "world".into());
    Response::json(&serde_json::json!({ "hello": name }))
}
"#;

pub fn readme(name: &str) -> String {
    format!(
        "# {name}\n\nA [Next Rust](https://github.com/iplustsolution/next-rust) application.\n\n```sh\nnext-rust dev     # http://localhost:3000\nnext-rust build   # production build + static generation\nnext-rust start   # run the production build\n```\n\nRoutes live in `app/`: `page.rs` files are pages, `layout.rs` files wrap their children, `route.rs` files are API endpoints.\n"
    )
}

/// Template for `next-rust generate <kind> <route>`: (file name, contents).
pub fn generate(kind: &str, route: &str) -> Option<(&'static str, String)> {
    let file = match kind {
        "page" => "page.rs",
        "layout" => "layout.rs",
        "template" => "template.rs",
        "loading" => "loading.rs",
        "error" => "error.rs",
        "not-found" => "not-found.rs",
        "api" | "route" => "route.rs",
        "middleware" => "middleware.rs",
        "metadata" => "metadata.rs",
        "default" => "default.rs",
        _ => return None,
    };
    let kind = if kind == "route" { "api" } else { kind };
    crate::scaffold::template(kind, &format!("/{}", route.trim_matches('/'))).map(|code| (file, code))
}

pub fn dockerfile(bin: &str, tailwind: bool) -> String {
    // Tailwind CSS projects download the Tailwind engine during the build
    // (with curl), cached between builds.
    let (curl, tailwind_cache) = if tailwind {
        (
            "RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates \\\n && rm -rf /var/lib/apt/lists/*\n",
            "    --mount=type=cache,target=/root/.cache/next-rust \\\n",
        )
    } else {
        ("", "")
    };
    format!(
        r#"# syntax=docker/dockerfile:1
# Generated by `next-rust docker`.
#
# The release binary carries the app's pages, configuration and static files,
# so the runtime image contains one file.

FROM rust:1-slim AS build
{curl}WORKDIR /src
COPY . .
ENV NEXT_RUST_EMBED=1 \
    CARGO_PROFILE_RELEASE_OPT_LEVEL=z \
    CARGO_PROFILE_RELEASE_LTO=fat \
    CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1 \
    CARGO_PROFILE_RELEASE_STRIP=symbols
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/src/target \
{tailwind_cache}    cargo build --release --bin {bin} \
 && cp target/release/{bin} /app

FROM gcr.io/distroless/cc-debian12:nonroot
COPY --from=build /app /app
ENV NEXT_RUST_ENV=production HOST=0.0.0.0 PORT=3000
EXPOSE 3000
ENTRYPOINT ["/app"]
"#
    )
}

pub const DOCKERIGNORE: &str = "target\n.next-rust\n.git\n.env*.local\n";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cargo_toml_for_each_framework_source() {
        let v = registry_requirement();
        assert_eq!(v.matches('.').count(), 1);
        let registry = cargo_toml("app", &FrameworkSource::Registry);
        assert!(registry.contains(&format!("next-rust = \"{v}\"")));
        assert!(registry.contains(&format!("next-rust-build = \"{v}\"")));
        let git = cargo_toml("app", &FrameworkSource::Git);
        assert!(git.contains("next-rust = { git = \"https://github.com/iplustsolution/next-rust\" }"));
        let path = cargo_toml("app", &FrameworkSource::Path("/src/next-rust/".into()));
        assert!(path.contains("next-rust = { path = \"/src/next-rust/crates/next-rust\" }"));
    }
}
