//! Project and file templates.

/// Where a new project gets the framework from.
pub enum FrameworkSource {
    /// A local checkout (`--framework-path`).
    Path(String),
    /// crates.io, pinned to this CLI's version.
    Registry,
    /// The GitHub repository's default branch.
    Git,
}

impl FrameworkSource {
    /// Human-readable description for terminal output.
    pub fn describe(&self) -> String {
        match self {
            FrameworkSource::Path(p) => format!("local checkout · {p}"),
            FrameworkSource::Registry => format!("crates.io · next-rust {}", env!("CARGO_PKG_VERSION")),
            FrameworkSource::Git => crate::REPO_URL.trim_start_matches("https://").to_owned(),
        }
    }
}

pub fn cargo_toml(name: &str, source: &FrameworkSource) -> String {
    let (dep, build_dep) = match source {
        FrameworkSource::Path(p) => (
            format!("{{ path = \"{}/crates/next-rust\" }}", p.trim_end_matches('/')),
            format!("{{ path = \"{}/crates/next-rust-build\" }}", p.trim_end_matches('/')),
        ),
        FrameworkSource::Registry => {
            (format!("\"{}\"", env!("CARGO_PKG_VERSION")), format!("\"{}\"", env!("CARGO_PKG_VERSION")))
        }
        FrameworkSource::Git => {
            (format!("{{ git = \"{}\" }}", crate::REPO_URL), format!("{{ git = \"{}\" }}", crate::REPO_URL))
        }
    };
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
next-rust = {dep}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"

[build-dependencies]
next-rust-build = {build_dep}

# Production builds: maximum optimization and a stripped binary without
# debug symbols. HTML pages and the browser runtime are minified automatically.
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
"#
    )
}

pub const BUILD_RS: &str = "fn main() {\n    next_rust_build::generate();\n}\n";

pub const CONFIG: &str = r#"# Next Rust configuration. Every setting is optional.

[app]
directory = "app"
# public = "public"

[server]
port = 3000

# [rendering]
# default = "auto"     # auto | static | dynamic
# streaming = true
"#;

pub const GITIGNORE: &str = "/target\n/.next-rust\n.env*.local\n";

pub const ENV_EXAMPLE: &str = "# Server-only secrets (never sent to the browser)\nDATABASE_URL=postgres://localhost/app\n\n# Values safe for client code must use the public prefix\nNEXT_RUST_PUBLIC_SITE_NAME=My App\n";

pub const API_RS: &str = r#"use next_rust::prelude::*;

pub async fn GET(req: Request) -> Response {
    let name = req.query_param("name").unwrap_or_else(|| "world".into());
    Response::json(&serde_json::json!({ "hello": name }))
}
"#;

pub fn readme(name: &str) -> String {
    format!(
        "# {name}\n\nA [Next Rust](https://github.com/iplustsolution/next-rust) application.\n\n```sh\nnext-rust dev     # http://localhost:3000\nnext-rust build   # production build + static generation\nnext-rust start   # run the production build\n```\n\nRoutes live in `app/`: `page.rs` files are pages, `layout.rs` files wrap their children, `route.rs` files are API endpoints.\n"
    )
}

/// Template for `next-rust generate <kind> <route>`: (file name, contents).
pub fn generate(kind: &str, route: &str) -> Option<(&'static str, String)> {
    let file = match kind {
        "page" => "page.rs",
        "layout" => "layout.rs",
        "template" => "template.rs",
        "loading" => "loading.rs",
        "error" => "error.rs",
        "not-found" => "not-found.rs",
        "api" | "route" => "route.rs",
        "middleware" => "middleware.rs",
        "metadata" => "metadata.rs",
        "default" => "default.rs",
        _ => return None,
    };
    let kind = if kind == "route" { "api" } else { kind };
    crate::scaffold::template(kind, &format!("/{}", route.trim_matches('/'))).map(|code| (file, code))
}

pub fn dockerfile(bin: &str) -> String {
    format!(
        r#"# syntax=docker/dockerfile:1
# Generated by `next-rust docker`.

FROM rust:1-slim AS build
WORKDIR /src
COPY . .
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/src/target \
    cargo build --release --bin {bin} \
 && cp target/release/{bin} /usr/local/bin/app \
 && mkdir -p public && (test -f next-rust.toml || touch next-rust.toml) \
 && NEXT_RUST_ENV=production /usr/local/bin/app --export

FROM debian:bookworm-slim AS runtime
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates \
 && rm -rf /var/lib/apt/lists/* \
 && useradd --system --uid 10001 app
WORKDIR /app
COPY --from=build /usr/local/bin/app /usr/local/bin/app
COPY --from=build /src/next-rust.toml ./
COPY --from=build /src/public ./public
COPY --from=build /src/.next-rust ./.next-rust
RUN mkdir -p /app/app && chown -R app /app/.next-rust
USER app
ENV NEXT_RUST_ENV=production HOST=0.0.0.0 PORT=3000
EXPOSE 3000
CMD ["/usr/local/bin/app"]
"#
    )
}

pub const DOCKERIGNORE: &str = "target\n.next-rust\n.git\n.env*.local\n";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cargo_toml_for_each_framework_source() {
        let v = env!("CARGO_PKG_VERSION");
        let registry = cargo_toml("app", &FrameworkSource::Registry);
        assert!(registry.contains(&format!("next-rust = \"{v}\"")));
        assert!(registry.contains(&format!("next-rust-build = \"{v}\"")));
        let git = cargo_toml("app", &FrameworkSource::Git);
        assert!(git.contains("next-rust = { git = \"https://github.com/iplustsolution/next-rust\" }"));
        let path = cargo_toml("app", &FrameworkSource::Path("/src/next-rust/".into()));
        assert!(path.contains("next-rust = { path = \"/src/next-rust/crates/next-rust\" }"));
    }
}
