//! Tailwind CSS, generated by the official Tailwind engine.
//!
//! When `[tailwind] enabled = true`, the build scans the app for class names
//! and compiles the CSS they need with Tailwind's standalone executable (no
//! Node.js). The executable for this machine is downloaded once, checked
//! against the checksum published with the release, and cached:
//!
//! * macOS / Linux: `$XDG_CACHE_HOME/next-rust` or `~/.cache/next-rust`
//! * Windows: `%LOCALAPPDATA%\next-rust`
//!
//! `NEXT_RUST_TAILWIND_BIN` points at an executable to use instead (offline
//! machines, locked-down CI). `NEXT_RUST_CACHE_DIR` moves the cache.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use next_rust_core::Config;
use next_rust_core::config::{TailwindDarkMode, TailwindUtility};

/// The Tailwind CSS release the framework uses.
pub const VERSION: &str = "4.3.3";

/// Release assets: (name, size in bytes, SHA-256), from the release's
/// `sha256sums.txt`.
const ASSETS: &[(&str, u64, &str)] = &[
    ("tailwindcss-linux-arm64", 109_881_488, "55fd0b241214eff3de1e8ee4f22796662f2d2e7a49bcfca7477cfd0bac398195"),
    ("tailwindcss-linux-arm64-musl", 105_492_344, "71ea4be79c9de9827545682df3e040053fb535d37c71ed2cfdedf9385a0868e0"),
    ("tailwindcss-linux-x64", 111_749_248, "dc61b3ac6b8c9ca874c0cc4c57b2409791a64c5540404ca5f5367360babc313a"),
    ("tailwindcss-linux-x64-musl", 108_529_952, "a04d34ceacc8f52cbe8920ad846cdeb61d3d0021dba32db0d1f77c9d9fad7a6c"),
    ("tailwindcss-macos-arm64", 79_826_018, "cdf646702987a743464dff4d9c60fd4480d1c1e73dd819a9a67f1078815dce9d"),
    ("tailwindcss-macos-x64", 83_656_784, "7922e0953f2110c05976e3bf58f14e643d90427575e766b7d433f5f80cbee7e1"),
    ("tailwindcss-windows-x64.exe", 112_503_296, "e0e260ce048014e9268f6237ff18f8ccf02cef521cbd0ae04e82c2cdf7aa3955"),
];

/// The release asset for this machine.
pub fn asset() -> Result<(&'static str, u64, &'static str), String> {
    let musl = cfg!(target_os = "linux")
        && (cfg!(target_env = "musl")
            || std::fs::read_dir("/lib")
                .is_ok_and(|d| d.flatten().any(|e| e.file_name().to_string_lossy().starts_with("ld-musl-"))));
    let name = match (std::env::consts::OS, std::env::consts::ARCH, musl) {
        ("macos", "aarch64", _) => "tailwindcss-macos-arm64",
        ("macos", "x86_64", _) => "tailwindcss-macos-x64",
        ("linux", "aarch64", false) => "tailwindcss-linux-arm64",
        ("linux", "aarch64", true) => "tailwindcss-linux-arm64-musl",
        ("linux", "x86_64", false) => "tailwindcss-linux-x64",
        ("linux", "x86_64", true) => "tailwindcss-linux-x64-musl",
        ("windows", "x86_64", _) => "tailwindcss-windows-x64.exe",
        (os, arch, _) => {
            return Err(format!(
                "Tailwind CSS has no standalone executable for {os}/{arch}; install one and set NEXT_RUST_TAILWIND_BIN"
            ));
        }
    };
    Ok(*ASSETS.iter().find(|(n, _, _)| *n == name).expect("every name above is in ASSETS"))
}

fn cache_dir() -> PathBuf {
    if let Some(dir) = std::env::var_os("NEXT_RUST_CACHE_DIR") {
        return PathBuf::from(dir);
    }
    if cfg!(windows)
        && let Some(local) = std::env::var_os("LOCALAPPDATA")
    {
        return Path::new(&local).join("next-rust");
    }
    if let Some(xdg) = std::env::var_os("XDG_CACHE_HOME") {
        return Path::new(&xdg).join("next-rust");
    }
    let home = std::env::var_os("HOME").or_else(|| std::env::var_os("USERPROFILE")).unwrap_or_default();
    Path::new(&home).join(".cache").join("next-rust")
}

/// Where the executable for this machine is (or will be) cached.
pub fn cached_path() -> Result<PathBuf, String> {
    let (name, _, _) = asset()?;
    Ok(cache_dir().join("tailwindcss").join(VERSION).join(name))
}

/// The executable to run, if it is already available (no download).
pub fn installed() -> Option<PathBuf> {
    if let Some(bin) = std::env::var_os("NEXT_RUST_TAILWIND_BIN") {
        return Some(PathBuf::from(bin));
    }
    let path = cached_path().ok()?;
    let marker = path.with_extension("verified");
    let (_, size, sha) = asset().ok()?;
    let ok = std::fs::read_to_string(&marker).is_ok_and(|m| m.trim() == sha)
        && std::fs::metadata(&path).is_ok_and(|m| m.len() == size);
    ok.then_some(path)
}

/// Download progress: bytes received so far and the total size.
pub type Progress<'a> = &'a mut dyn FnMut(u64, u64);

/// The Tailwind executable, downloading and verifying it on first use.
pub fn ensure(progress: Progress) -> Result<PathBuf, String> {
    if let Ok(path) = cached_path()
        && let Some(dir) = path.parent()
    {
        remove_stale_downloads(dir);
    }
    if let Some(bin) = installed() {
        return Ok(bin);
    }
    let (name, size, sha) = asset()?;
    let path = cached_path()?;
    let dir = path.parent().ok_or("invalid cache path")?;
    std::fs::create_dir_all(dir).map_err(|e| format!("cannot create {}: {e}", dir.display()))?;
    let partial = path.with_extension(format!("download-{}", std::process::id()));
    let url = format!("https://github.com/tailwindlabs/tailwindcss/releases/download/v{VERSION}/{name}");

    let mut child = Command::new(if cfg!(windows) { "curl.exe" } else { "curl" })
        .args(["--fail", "--location", "--silent", "--show-error", "--retry", "2", "--output"])
        .arg(&partial)
        .arg(&url)
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| {
            format!(
                "Tailwind CSS needs to download its engine, but curl could not be started ({e}). Install curl, or \
                 download {url} yourself and set NEXT_RUST_TAILWIND_BIN to its path"
            )
        })?;
    let status = loop {
        progress(std::fs::metadata(&partial).map(|m| m.len()).unwrap_or(0), size);
        match child.try_wait() {
            Ok(Some(status)) => break status,
            Ok(None) => std::thread::sleep(std::time::Duration::from_millis(100)),
            Err(e) => return Err(e.to_string()),
        }
    };
    if !status.success() {
        let mut err = String::new();
        if let Some(mut stderr) = child.stderr.take() {
            let _ = std::io::Read::read_to_string(&mut stderr, &mut err);
        }
        let _ = std::fs::remove_file(&partial);
        return Err(format!(
            "downloading Tailwind CSS {VERSION} failed: {}\n  from {url}\n  (offline? download it elsewhere and set NEXT_RUST_TAILWIND_BIN)",
            err.trim()
        ));
    }
    progress(size, size);

    let bytes = std::fs::read(&partial).map_err(|e| e.to_string())?;
    let actual = sha256_hex(&bytes);
    if actual != sha {
        let _ = std::fs::remove_file(&partial);
        return Err(format!(
            "the downloaded Tailwind CSS executable does not match the published checksum (expected {sha}, got {actual}); it was deleted"
        ));
    }
    drop(bytes);
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&partial, std::fs::Permissions::from_mode(0o755)).map_err(|e| e.to_string())?;
    }
    std::fs::rename(&partial, &path).map_err(|e| e.to_string())?;
    std::fs::write(path.with_extension("verified"), sha).map_err(|e| e.to_string())?;
    Ok(path)
}

/// Deletes partial downloads left behind by builds that were killed mid-download
/// (a cancelled `cargo build`, an editor restarting its build). Recent ones are
/// kept: another build may still be writing them.
fn remove_stale_downloads(dir: &Path) {
    let Ok(entries) = std::fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let stale = entry.file_name().to_string_lossy().contains(".download-")
            && entry
                .metadata()
                .and_then(|m| m.modified())
                .is_ok_and(|t| t.elapsed().is_ok_and(|age| age.as_secs() > 600));
        if stale {
            let _ = std::fs::remove_file(entry.path());
        }
    }
}

/// The Tailwind input stylesheet for this configuration.
pub fn input_css(config: &Config) -> String {
    let tw = &config.tailwind;
    let quote = |p: &Path| format!("\"{}\"", p.to_string_lossy().replace('\\', "/").replace('"', "\\\""));
    let mut css = String::from("/* Generated by Next Rust from [tailwind] in next-rust.toml. */\n");
    if tw.preflight {
        css.push_str("@import \"tailwindcss\" source(none);\n");
    } else {
        css.push_str("@layer theme, base, components, utilities;\n");
        css.push_str("@import \"tailwindcss/theme.css\" layer(theme);\n");
        css.push_str("@import \"tailwindcss/utilities.css\" layer(utilities) source(none);\n");
    }
    // Imports must come before other rules; Tailwind still applies variants
    // and theme values declared further down to the imported files.
    for sheet in stylesheet_paths(config) {
        let _ = writeln!(css, "@import {};", quote(&sheet));
    }
    let mut sources = vec![config.app_dir(), config.root.join("src")];
    sources.extend(tw.sources.iter().map(|s| config.resolve(s)));
    for dir in sources.iter().filter(|d| d.exists()) {
        let _ = writeln!(css, "@source {};", quote(dir));
    }
    for class in &tw.safelist {
        let _ = writeln!(css, "@source inline({});", quote(Path::new(class)));
    }
    for plugin in &tw.plugins {
        let _ = writeln!(css, "@plugin {};", quote(Path::new(plugin)));
    }
    match tw.dark_mode {
        TailwindDarkMode::Media => {}
        TailwindDarkMode::Class => css.push_str("@custom-variant dark (&:where(.dark, .dark *));\n"),
        TailwindDarkMode::Attribute => {
            css.push_str("@custom-variant dark (&:where([data-theme=dark], [data-theme=dark] *));\n")
        }
    }
    for (name, selector) in &tw.variants {
        let _ = writeln!(css, "@custom-variant {name} ({selector});");
    }
    if !tw.theme.is_empty() {
        css.push_str("@theme {\n");
        for (key, value) in &tw.theme {
            let _ = writeln!(css, "  --{}: {value};", key.trim_start_matches("--"));
        }
        css.push_str("}\n");
    }
    for (name, utility) in &tw.utilities {
        let _ = writeln!(css, "@utility {name} {{");
        match utility {
            TailwindUtility::Apply(classes) => {
                let _ = writeln!(css, "  @apply {classes};");
            }
            TailwindUtility::Declarations(decls) => {
                for (property, value) in decls {
                    let _ = writeln!(css, "  {property}: {value};");
                }
            }
        }
        css.push_str("}\n");
    }
    if !tw.css.trim().is_empty() {
        css.push_str(&tw.css);
        css.push('\n');
    }
    css
}

/// The `[tailwind] stylesheets`, resolved against the config file, in order.
pub fn stylesheet_paths(config: &Config) -> Vec<PathBuf> {
    config.tailwind.stylesheets.iter().map(|s| config.resolve(s)).collect()
}

/// Directories Tailwind scans; a change in any of them regenerates the CSS.
pub fn scanned_dirs(config: &Config) -> Vec<PathBuf> {
    let mut dirs = vec![config.app_dir(), config.root.join("src")];
    dirs.extend(config.tailwind.sources.iter().map(|s| config.resolve(s)));
    dirs.into_iter().filter(|d| d.exists()).collect()
}

/// Compile the CSS for `config` into `out_dir/next_rust_tailwind.css`,
/// returning the CSS.
pub fn compile(bin: &Path, config: &Config, out_dir: &Path, minify: bool) -> Result<String, String> {
    std::fs::create_dir_all(out_dir).map_err(|e| e.to_string())?;
    let input = out_dir.join("next_rust_tailwind.input.css");
    let output = out_dir.join("next_rust_tailwind.css");
    std::fs::write(&input, input_css(config)).map_err(|e| e.to_string())?;
    let mut cmd = Command::new(bin);
    cmd.arg("--input").arg(&input).arg("--output").arg(&output).current_dir(&config.root);
    if minify {
        cmd.arg("--minify");
    }
    let result = cmd.output().map_err(|e| format!("could not run Tailwind CSS ({}): {e}", bin.display()))?;
    if !result.status.success() {
        return Err(format!("Tailwind CSS failed:\n{}", String::from_utf8_lossy(&result.stderr).trim()));
    }
    std::fs::read_to_string(&output).map_err(|e| e.to_string())
}

/// SHA-256 of `data` as lowercase hex.
pub fn sha256_hex(data: &[u8]) -> String {
    const K: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5, 0xd807aa98,
        0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786,
        0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8,
        0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
        0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819,
        0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a,
        0x5b9cca4f, 0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
        0xc67178f2,
    ];
    let mut h: [u32; 8] =
        [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19];
    let mut block = |chunk: &[u8; 64]| {
        let mut w = [0u32; 64];
        for (i, word) in chunk.as_chunks::<4>().0.iter().enumerate() {
            w[i] = u32::from_be_bytes(*word);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16].wrapping_add(s0).wrapping_add(w[i - 7]).wrapping_add(s1);
        }
        let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut hh] = h;
        for i in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ (!e & g);
            let t1 = hh.wrapping_add(s1).wrapping_add(ch).wrapping_add(K[i]).wrapping_add(w[i]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let t2 = s0.wrapping_add(maj);
            hh = g;
            g = f;
            f = e;
            e = d.wrapping_add(t1);
            d = c;
            c = b;
            b = a;
            a = t1.wrapping_add(t2);
        }
        for (x, y) in h.iter_mut().zip([a, b, c, d, e, f, g, hh]) {
            *x = x.wrapping_add(y);
        }
    };
    let (blocks, rest) = data.as_chunks::<64>();
    for chunk in blocks {
        block(chunk);
    }
    let mut tail = rest.to_vec();
    tail.push(0x80);
    while tail.len() % 64 != 56 {
        tail.push(0);
    }
    tail.extend_from_slice(&((data.len() as u64) * 8).to_be_bytes());
    for chunk in tail.as_chunks::<64>().0 {
        block(chunk);
    }
    h.iter().map(|v| format!("{v:08x}")).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sha256_known_vectors() {
        assert_eq!(sha256_hex(b""), "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");
        assert_eq!(sha256_hex(b"abc"), "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad");
        let long = vec![b'a'; 1_000_000];
        assert_eq!(sha256_hex(&long), "cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0");
        assert_eq!(sha256_hex(&[7u8; 55]).len(), 64);
        assert_eq!(sha256_hex(&[7u8; 64]).len(), 64);
    }

    #[test]
    fn this_machine_has_an_asset() {
        if let Ok((name, size, sha)) = asset() {
            assert!(name.starts_with("tailwindcss-") && size > 1_000_000 && sha.len() == 64);
        }
    }

    #[test]
    fn input_css_from_configuration() {
        let mut config = Config::from_toml_str(
            r##"
            [tailwind]
            enabled = true
            dark_mode = "class"
            plugins = ["@tailwindcss/typography"]
            safelist = ["bg-red-500"]
            css = "@keyframes wiggle { from { rotate: -3deg } to { rotate: 3deg } }"

            [tailwind.theme]
            color-brand = "#f26b2a"
            "--font-display" = "Inter, sans-serif"

            [tailwind.utilities]
            btn = "rounded-lg bg-brand px-4 py-2"
            content-auto = { content-visibility = "auto" }

            [tailwind.variants]
            theme-midnight = "&:where([data-theme=midnight] *)"
            "##,
        )
        .unwrap();
        let root = std::env::temp_dir().join(format!("nr-tw-{}", std::process::id()));
        std::fs::create_dir_all(root.join("app")).unwrap();
        config.root = root.clone();
        let css = input_css(&config);
        for needle in [
            "@import \"tailwindcss\" source(none);",
            "/app\";",
            "@source inline(\"bg-red-500\");",
            "@plugin \"@tailwindcss/typography\";",
            "@custom-variant dark (&:where(.dark, .dark *));",
            "@custom-variant theme-midnight (&:where([data-theme=midnight] *));",
            "  --color-brand: #f26b2a;",
            "  --font-display: Inter, sans-serif;",
            "@utility btn {\n  @apply rounded-lg bg-brand px-4 py-2;\n}",
            "@utility content-auto {\n  content-visibility: auto;\n}",
            "@keyframes wiggle",
        ] {
            assert!(css.contains(needle), "missing `{needle}` in:\n{css}");
        }
        assert!(!css.contains("/src\""), "missing directories are not scanned");
        config.tailwind.preflight = false;
        assert!(input_css(&config).contains("tailwindcss/utilities.css\" layer(utilities) source(none)"));
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn stylesheets_are_imported_first_and_in_order() {
        let mut config = Config::from_toml_str(
            "[tailwind]\nenabled = true\nstylesheets = [\"styles/theme.css\", \"styles/animate.css\"]\n",
        )
        .unwrap();
        let root = std::env::temp_dir().join(format!("nr-tw-sheets-{}", std::process::id()));
        std::fs::create_dir_all(root.join("app")).unwrap();
        config.root = root.clone();
        let css = input_css(&config);
        let at = |needle: &str| css.find(needle).unwrap_or_else(|| panic!("missing `{needle}` in:\n{css}"));
        let tailwind = at("@import \"tailwindcss\"");
        let theme = at("/styles/theme.css\";");
        let animate = at("/styles/animate.css\";");
        let source = at("@source ");
        assert!(tailwind < theme && theme < animate && animate < source, "wrong order:\n{css}");
        assert_eq!(stylesheet_paths(&config), [root.join("styles/theme.css"), root.join("styles/animate.css")]);
        std::fs::remove_dir_all(root).unwrap();
    }
}
