//! The "cli" documentation page.

use next_rust::prelude::*;

pub fn content() -> Node {
    fragment![
        pre![code![class("language-text"), r"next-rust <COMMAND> [OPTIONS]"]],
        p![
            "The CLI depends only on the standard library and the framework's own crates (no argument-parsing library, no async runtime). It drives ",
            code!["cargo"],
            " for compilation.",
        ],
        h2![id("new-name"), a![class("anchor"), href("#new-name"), code!["new <name>"]]],
        p![
            "Creates a project: ",
            code!["Cargo.toml"],
            ", ",
            code!["build.rs"],
            ", ",
            code!["src/main.rs"],
            ", ",
            code!["next-rust.toml"],
            ", ",
            code!["app/"],
            " with a layout, two pages, a 404 page and an API route, plus ",
            code!["public/"],
            ", ",
            code![".gitignore"],
            " and ",
            code![".env.example"],
            ".",
        ],
        p!["By default the project depends on ", code!["https://github.com/iplustsolution/next-rust"], "."],
        div![
            class("table-wrap"),
            table![
                thead![tr![th!["option"], th![]]],
                tbody![tr![
                    td![code!["--framework-path <dir>"]],
                    td!["depend on a local Next Rust checkout (path dependencies) instead"],
                ],],
            ],
        ],
        h2![id("dev"), a![class("anchor"), href("#dev"), code!["dev"]]],
        p!["Development server:"],
        ul![
            li!["validates routes on every change and prints readable diagnostics;"],
            li![
                "rebuilds incrementally with ",
                code!["cargo build"],
                ". While it compiles, and after a compile error, ",
                strong!["the previous server keeps serving"],
                ";",
            ],
            li!["restarts the server after a successful build. Connected browsers reconnect and reload automatically;",],
            li![
                "sends compile errors to the browser as an overlay (",
                code![".next-rust/dev/status.json"],
                ", streamed via ",
                code!["/_nr/dev/events"],
                ");",
            ],
            li!["reloads the browser without a rebuild when ", code!["public/"], " or ", code!["client/"], " change;",],
            li!["prints ", code!["route added"], " / ", code!["route removed"], " when files appear or disappear;",],
            li![
                strong!["fills new empty special files with starter code."],
                " Create an empty ",
                code!["app/about/page.rs"],
                " and it becomes a working ",
                code!["/about"],
                " page within a moment. The same goes for ",
                code!["layout.rs"],
                ", ",
                code!["route.rs"],
                ", ",
                code!["loading.rs"],
                ", ",
                code!["error.rs"],
                ", ",
                code!["not-found.rs"],
                ", ",
                code!["middleware.rs"],
                ", ",
                code!["template.rs"],
                ", ",
                code!["metadata.rs"],
                " and ",
                code!["default.rs"],
                ". Only brand-new, empty files are filled: files with content, files you empty later, and files in ",
                code!["_private"],
                " folders are never touched. Turn it off with ",
                code!["[dev] scaffold = false"],
                ".",
            ],
        ],
        p![
            "Watched for rebuilds: the app directory, ",
            code!["src/"],
            ", ",
            code!["assets/"],
            ", ",
            code!["build.rs"],
            ", ",
            code!["Cargo.toml"],
            ", the config file, ",
            code!["[api] directory"],
            " and ",
            code!["[dev] watch"],
            ". Watching uses polling (",
            code!["[dev] poll_interval"],
            "), which works the same on every platform, over network filesystems and in containers.",
        ],
        div![
            class("table-wrap"),
            table![
                thead![tr![th!["option"], th![]]],
                tbody![tr![td![code!["--port, -p <port>"]], td!["port (default from config)"]]],
            ],
        ],
        h2![id("build"), a![class("anchor"), href("#build"), code!["build"]]],
        ol![
            li!["validates routes (fails on errors);"],
            li![
                code!["cargo build --release"],
                " with ",
                code!["next-rust.toml"],
                ", ",
                code!["public/"],
                ", ",
                code!["assets/"],
                " and ",
                code!["client/"],
                " embedded, fat LTO, one codegen unit and stripped symbols (unless your ",
                code!["Cargo.toml"],
                " has its own ",
                code!["[profile.release]"],
                ");",
            ],
            li!["copies the binary to ", code![".next-rust/<name>"], ", the only file the build writes there;",],
            li![
                "runs it from an empty directory with ",
                code!["--export"],
                ", which renders every static page in memory, so rendering errors and missing files fail the build;",
            ],
            li![
                "writes the route manifest and render report for ",
                code!["next-rust analyze"],
                " to ",
                code!["target/next-rust/"],
                ";",
            ],
            li!["prints a summary:"],
        ],
        pre![code![
            class("language-text"),
            r"Route                                              Size
○ /                                               705 B  1 page
○ /blog/:slug                                     2.1 kB  12 pages · revalidate 3600s
ƒ /api/hello                                             api
λ /products/:id                                          dynamic segment without generate_params

○  static (pre-rendered)   λ  dynamic (server-rendered)   ƒ  API",
        ],],
        div![
            class("table-wrap"),
            table![
                thead![tr![th!["option"], th![]]],
                tbody![tr![td![code!["--no-check"]], td!["skip rendering static pages after compiling"]]],
            ],
        ],
        h2![id("start"), a![class("anchor"), href("#start"), code!["start"]]],
        p![
            "Runs ",
            code![".next-rust/<name>"],
            " with ",
            code!["NEXT_RUST_ENV=production"],
            ". ",
            code!["--port"],
            " overrides the port.",
        ],
        h2![id("check"), a![class("anchor"), href("#check"), code!["check"]]],
        p!["Validates routes and special-file exports, then runs ", code!["cargo check"], "."],
        h2![id("routes"), a![class("anchor"), href("#routes"), code!["routes"]]],
        p!["Prints the route table."],
        div![
            class("table-wrap"),
            table![
                thead![tr![th!["option"], th![]]],
                tbody![
                    tr![td![code!["--layouts"]], td!["layout chain and the reason a route is dynamic"]],
                    tr![td![code!["--tree"]], td!["the scanned directory tree with special files"]],
                    tr![td![code!["--json"]], td!["the route manifest (same format as ", code!["routes.json"], ")"],],
                ],
            ],
        ],
        h2![id("analyze"), a![class("anchor"), href("#analyze"), code!["analyze"]]],
        p![
            "Reads the last build's reports from ",
            code!["target/next-rust/"],
            ": static/dynamic/API counts, pre-rendered page sizes (largest first) with render times, on-demand routes, and binary size.",
        ],
        h2![
            id("generate-kind-route"),
            a![class("anchor"), href("#generate-kind-route"), code!["generate <kind> <route>"]],
        ],
        p![
            "Scaffolds a special file. Kinds: ",
            code!["page"],
            ", ",
            code!["layout"],
            ", ",
            code!["template"],
            ", ",
            code!["loading"],
            ", ",
            code!["error"],
            ", ",
            code!["not-found"],
            ", ",
            code!["api"],
            ", ",
            code!["middleware"],
            ".",
        ],
        pre![code![
            class("language-sh"),
            r"next-rust generate page /products/[id]
next-rust generate api /api/orders
next-rust generate loading /dashboard",
        ],],
        h2![id("editor"), a![class("anchor"), href("#editor"), code!["editor"]]],
        p!["Adds editor support for VS Code:"],
        ul![
            li![
                code![".vscode/next-rust.code-snippets"],
                ": type a prefix and pick the suggestion. ",
                code!["nrpage"],
                ", ",
                code!["nrparams"],
                ", ",
                code!["nrlayout"],
                ", ",
                code!["nrroute"],
                ", ",
                code!["nrget"],
                ", ",
                code!["nrpost"],
                ", ",
                code!["nrmeta"],
                ", ",
                code!["nrload"],
                ", ",
                code!["nraction"],
                ", ",
                code!["nrform"],
                ", ",
                code!["nrloading"],
                ", ",
                code!["nrerror"],
                ", ",
                code!["nrnotfound"],
                ", ",
                code!["nrmiddleware"],
                ", ",
                code!["nrcomponent"],
                ", ",
                code!["nrlink"],
                ", ",
                code!["nrimage"],
                ", ",
                code!["nrcss"],
                ".",
            ],
            li![
                code![".vscode/extensions.json"],
                ": recommends rust-analyzer, which provides completion for everything in ",
                code!["next_rust::prelude"],
                " (element macros, attributes, extractors, ",
                code!["Response"],
                ", …).",
            ],
            li![
                code![".vscode/settings.json"],
                ": re-runs build scripts on save, so a page you just created is part of the crate, and gets completions, right away.",
            ],
        ],
        p!["New projects include these files. Existing files are kept unless ", code!["--force"], "."],
        h2![id("doctor"), a![class("anchor"), href("#doctor"), code!["doctor"]]],
        p![
            "Checks the toolchain (rustc ≥ 1.88), configuration, ",
            code!["build.rs"],
            " and ",
            code!["src/main.rs"],
            " wiring, the ",
            code!["next-rust-build"],
            " dependency, ",
            code![".env"],
            " git-ignore, port availability, and route diagnostics.",
        ],
        h2![id("docker"), a![class("anchor"), href("#docker"), code!["docker"]]],
        p![
            "Writes a multi-stage ",
            code!["Dockerfile"],
            " and ",
            code![".dockerignore"],
            ". See ",
            a![href("/docs/deployment"), "deployment"],
            ". ",
            code!["--force"],
            " overwrites existing files.",
        ],
        h2![id("upgrade"), a![class("anchor"), href("#upgrade"), code!["upgrade"]]],
        p!["Updates to the latest Next Rust on GitHub."],
        div![
            class("table-wrap"),
            table![
                thead![tr![th!["option"], th![]]],
                tbody![
                    tr![td![em!["(none)"]], td!["both of the below"]],
                    tr![
                        td![code!["--project"]],
                        td![
                            code!["cargo update -p next-rust -p next-rust-build"],
                            " in the current project, reporting the old and new commit",
                        ],
                    ],
                    tr![
                        td![code!["--cli"]],
                        td![code![
                            "cargo install --git https://github.com/iplustsolution/next-rust next-rust-cli --force",
                        ],],
                    ],
                ],
            ],
        ],
        p![
            "Projects that use ",
            code!["--framework-path"],
            " are updated with ",
            code!["git pull"],
            " in that checkout. ",
            code!["upgrade"],
            " says so instead of changing anything.",
        ],
        h3![id("update-notice"), a![class("anchor"), href("#update-notice"), "Update notice"]],
        p![
            "Once every 24 hours, ",
            code!["dev"],
            " and ",
            code!["new"],
            " check GitHub for a newer version: the workspace version in ",
            code!["Cargo.toml"],
            ", and the latest commit compared with your ",
            code!["Cargo.lock"],
            ". If something is newer, they print a note suggesting ",
            code!["next-rust upgrade"],
            ". The check:",
        ],
        ul![
            li!["never installs or changes anything;"],
            li![
                "sends nothing about you or your project (it downloads one public file and runs ",
                code!["git ls-remote"],
                ");",
            ],
            li!["gives up silently after about 5 seconds or on any error;"],
            li!["is skipped when ", code!["CI"], " or ", code!["NEXT_RUST_NO_UPDATE_CHECK"], " is set."],
        ],
        p!["The time of the last check is stored in ", code!["~/.next-rust/last-update-check"], "."],
        h2![id("clean"), a![class("anchor"), href("#clean"), code!["clean"]]],
        p!["Removes the build output directory. It refuses to delete a directory outside the project."],
        h2![id("exit-codes"), a![class("anchor"), href("#exit-codes"), "Exit codes"]],
        p![code!["0"], " success, ", code!["1"], " failure (diagnostics were printed)."],
    ]
}
