//! The "security" documentation page.

use next_rust::prelude::*;

pub fn content() -> Node {
    fragment![
        p![
            "This page describes the framework's defaults and reports the pre-1.0 audit of each area named in the project requirements. \"Tested\" means an automated test in this repository covers the behaviour.",
        ],
        h2![id("defaults-at-a-glance"), a![class("anchor"), href("#defaults-at-a-glance"), "Defaults at a glance"],],
        div![
            class("table-wrap"),
            table![
                thead![tr![th!["area"], th!["default"]]],
                tbody![
                    tr![
                        td!["HTML output"],
                        td!["all text and attributes escaped; ", code!["raw_html"], " is explicit"],
                    ],
                    tr![
                        td!["URL attributes"],
                        td![
                            code!["javascript:"],
                            ", ",
                            code!["vbscript:"],
                            ", non-image ",
                            code!["data:"],
                            " neutralized",
                        ],
                    ],
                    tr![td!["Event handler attributes"], td!["dropped unless ", code!["raw_attr"]]],
                    tr![
                        td!["Response headers"],
                        td![
                            code!["X-Content-Type-Options: nosniff"],
                            ", ",
                            code!["X-Frame-Options: SAMEORIGIN"],
                            ", ",
                            code!["Referrer-Policy: strict-origin-when-cross-origin"],
                            ", ",
                            code!["Cross-Origin-Opener-Policy: same-origin"],
                            ", restrictive ",
                            code!["Permissions-Policy"],
                        ],
                    ],
                    tr![
                        td!["CSP"],
                        td![
                            "opt-in via ",
                            code!["[security] csp"],
                            "; framework inline scripts always carry a per-request nonce",
                        ],
                    ],
                    tr![
                        td!["Cookies"],
                        td![
                            code!["HttpOnly"],
                            ", ",
                            code!["SameSite=Lax"],
                            ", ",
                            code!["Path=/"],
                            ", ",
                            code!["Secure"],
                            " outside development",
                        ],
                    ],
                    tr![td!["Server actions"], td!["POST-only, cross-site requests rejected"]],
                    tr![td!["Request bodies"], td!["2 MiB limit; header read timeout 10 s; request timeout 60 s"],],
                    tr![td!["Errors"], td!["details only in development; production shows a digest"]],
                    tr![td!["Static files"], td!["traversal-safe resolver, no dotfiles, no directory listings"],],
                    tr![td!["Secrets"], td!["only ", code!["NEXT_RUST_PUBLIC_*"], " variables can reach clients"],],
                ],
            ],
        ],
        h2![id("audit"), a![class("anchor"), href("#audit"), "Audit"]],
        h3![
            id("path-traversal-directory-traversal-static-file-serving-pass-tested"),
            a![
                class("anchor"),
                href("#path-traversal-directory-traversal-static-file-serving-pass-tested"),
                "Path traversal / directory traversal / static file serving — ",
                strong!["pass (tested)"],
            ],
        ],
        p![
            code!["static_files::resolve_safe"],
            " percent-decodes each segment. It rejects ",
            code!["."],
            ", ",
            code![".."],
            ", empty segments, segments starting with ",
            code!["."],
            ", backslashes, NUL bytes and ",
            code![":"],
            ", before touching the filesystem. It then canonicalizes the result and requires it to stay under the canonical root, which defeats symlink escapes. Only regular files are served.",
        ],
        p![
            "Tests cover ",
            code!["/../"],
            ", ",
            code!["%2e%2e"],
            ", ",
            code!["..%2F"],
            ", backslash, NUL, dotfiles, directories and symlinks pointing outside the root (",
            code!["static_files::tests"],
            ", ",
            code!["tests/pipeline.rs::public_files"],
            "). The same resolver serves ",
            code!["/_nr/client/"],
            ", ",
            code!["/_nr/assets/"],
            " and ",
            code!["/_nr/image"],
            ".",
        ],
        h3![
            id("html-escaping-template-injection-xss-pass-tested"),
            a![
                class("anchor"),
                href("#html-escaping-template-injection-xss-pass-tested"),
                "HTML escaping, template injection, XSS — ",
                strong!["pass (tested)"],
            ],
        ],
        ul![
            li![
                "The DSL escapes text (",
                code!["& < >"],
                ") and attribute values (",
                code!["& < > \" '"],
                "). Templates are Rust code, not strings, so there is no template language to inject into.",
            ],
            li![
                "URL attributes are checked by ",
                code!["is_safe_url"],
                ", which ignores control characters and whitespace so ",
                code!["java\\tscript:"],
                " is caught.",
            ],
            li![
                code!["attr(\"onclick\", ..)"],
                " is dropped. Attribute names with quotes, spaces, ",
                code!["="],
                ", ",
                code!["/"],
                " or ",
                code![">"],
                " are dropped.",
            ],
            li![
                "Text inside ",
                code!["<script>"],
                "/",
                code!["<style>"],
                " is escaped against ",
                code!["</script"],
                " breakouts.",
            ],
            li!["Metadata values are escaped. Unsafe canonical/link URLs become ", code!["#"], "."],
            li!["Island props are JSON inside an attribute, escaped as attribute text."],
            li!["Streaming redirect scripts embed the location via JSON encoding with ", code!["</"], " escaped.",],
        ],
        p![
            "Residual risk: ",
            code!["raw_html"],
            ", ",
            code!["raw_attr"],
            ", plugin ",
            code!["head()"],
            " markup and the contents of ",
            code!["script!"],
            " elements you write are trusted by design.",
        ],
        h3![
            id("csrf-pass-for-server-actions-tested-opt-in-elsewhere"),
            a![
                class("anchor"),
                href("#csrf-pass-for-server-actions-tested-opt-in-elsewhere"),
                "CSRF — ",
                strong!["pass for server actions (tested); opt-in elsewhere"],
            ],
        ],
        p![
            "Server actions check ",
            code!["Sec-Fetch-Site"],
            "/",
            code!["Origin"],
            " against ",
            code!["Host"],
            ". Plain API routes aren't automatically CSRF-protected, because many are called cross-origin by design. Use ",
            code!["csrf()"],
            " middleware (double-submit token, constant-time comparison) or SameSite cookies as appropriate.",
        ],
        h3![id("ssrf-pass"), a![class("anchor"), href("#ssrf-pass"), "SSRF — ", strong!["pass"]]],
        p![
            "The framework makes no outbound requests on behalf of clients. The image endpoint accepts only local paths starting with ",
            code!["/"],
            " (not ",
            code!["//"],
            ") and resolves them inside ",
            code!["public/"],
            ". Remote ",
            code!["Image!"],
            " sources are emitted as plain ",
            code!["src"],
            " attributes and never fetched by the server.",
        ],
        h3![
            id("request-smuggling-delegated-to-hyper"),
            a![
                class("anchor"),
                href("#request-smuggling-delegated-to-hyper"),
                "Request smuggling — ",
                strong!["delegated to hyper"],
            ],
        ],
        p![
            "HTTP parsing, ",
            code!["Content-Length"],
            "/",
            code!["Transfer-Encoding"],
            " handling and connection management are done by hyper 1.x, which rejects ambiguous framing. The framework doesn't parse HTTP itself. Deploy behind proxies that normalize requests, the standard advice for any origin server.",
        ],
        h3![
            id("header-injection-pass-tested"),
            a![class("anchor"), href("#header-injection-pass-tested"), "Header injection — ", strong!["pass (tested)"],],
        ],
        p![
            "All header writes go through ",
            code!["http::HeaderValue"],
            ", which rejects CR/LF. ",
            code!["Response::set_header"],
            " drops invalid values and logs a warning. Redirect locations use the same validation. Cookie names, values and attributes are validated (",
            code!["cookies::tests"],
            "). SSE event names and ids have newlines stripped.",
        ],
        h3![
            id("cookie-security-pass-tested"),
            a![class("anchor"), href("#cookie-security-pass-tested"), "Cookie security — ", strong!["pass (tested)"],],
        ],
        p![
            "Defaults are ",
            code!["HttpOnly; SameSite=Lax; Path=/"],
            ", plus ",
            code!["Secure"],
            " outside development. ",
            code!["SameSite=None"],
            " always adds ",
            code!["Secure"],
            ". Session ids are 256 bits from the OS CSPRNG (",
            code!["getrandom"],
            "). Session data is server-side, and ",
            code!["Session::regenerate"],
            " exists to prevent fixation. Flash cookies used for form errors expire after 60 seconds and never contain password- or token-like fields.",
        ],
        h3![
            id("secret-exposure-client-bundle-leakage-pass-with-caveats"),
            a![
                class("anchor"),
                href("#secret-exposure-client-bundle-leakage-pass-with-caveats"),
                "Secret exposure / client bundle leakage — ",
                strong!["pass, with caveats"],
            ],
        ],
        ul![
            li![
                "Server code is compiled only into the server binary. The framework doesn't build client bundles from application code.",
            ],
            li![
                code!["#[server]"],
                " and ",
                code!["#[server_action]"],
                " items are compiled out on ",
                code!["wasm32"],
                ", so WASM client crates can't accidentally include them.",
            ],
            li![
                "Environment variables reach HTML only if prefixed with ",
                code!["NEXT_RUST_PUBLIC_"],
                ", and only on pages with islands.",
            ],
            li![
                "Caveats: ",
                code!["#[client]"],
                " component props are serialized into the page, so never pass secrets as props. Anything you render into HTML is public.",
            ],
            li![
                "Static pages that read request data fail to render (",
                code!["DynamicUsage"],
                ") instead of caching one user's data for everyone (tested).",
            ],
        ],
        h3![
            id("file-uploads-limited-by-design"),
            a![
                class("anchor"),
                href("#file-uploads-limited-by-design"),
                "File uploads — ",
                strong!["limited by design"],
            ],
        ],
        p![
            "Bodies are capped (",
            code!["body_limit"],
            ", ",
            code!["Content-Length"],
            " checked early, streaming limit enforced during reads). Server actions reject multipart. No upload parser is bundled. Use ",
            code!["req.take_body()"],
            " with a vetted multipart crate in an API route, store files outside ",
            code!["public/"],
            ", and validate type and size.",
        ],
        h3![
            id("denial-of-service-basic-protections"),
            a![
                class("anchor"),
                href("#denial-of-service-basic-protections"),
                "Denial of service — ",
                strong!["basic protections"],
            ],
        ],
        ul![
            li!["header read timeout (slowloris), request timeout, graceful shutdown;"],
            li!["body size limits;"],
            li!["bounded caches (", code!["MemoryStore"], " LRU) and a bounded rate-limit map;"],
            li!["ISR regeneration deduplicated per path;"],
            li!["the dev-only endpoints (", code!["/_nr/dev/*"], ") are disabled outside development (tested).",],
        ],
        p!["Not provided: connection limits per IP, or distributed rate limiting. Use a proxy or CDN."],
        h3![
            id("error-information-leakage-pass-tested"),
            a![
                class("anchor"),
                href("#error-information-leakage-pass-tested"),
                "Error information leakage — ",
                strong!["pass (tested)"],
            ],
        ],
        p![
            "In production, internal errors render a generic page with a random digest that is also logged. Details (messages, source file) appear only in development (",
            code!["tests/pipeline.rs::error_boundaries_and_global_errors"],
            ").",
        ],
        h2![
            id("reporting-vulnerabilities"),
            a![class("anchor"), href("#reporting-vulnerabilities"), "Reporting vulnerabilities"],
        ],
        p![
            "Please report security issues privately to the maintainers before disclosure. Until a dedicated address exists, open a GitHub security advisory on the repository.",
        ],
    ]
}
