//! The "status" documentation page.

use next_rust::prelude::*;

pub fn content() -> Node {
    fragment![
        p![
            "Next Rust is pre-1.0: every push to ",
            code!["main"],
            " is released automatically as a new ",
            code!["0.0.x"],
            " version, and the public API may still change.",
        ],
        p![
            "Legend: ✅ implemented and covered by tests · 🟡 implemented with documented limitations · ❌ not implemented yet",
        ],
        h2![id("routing"), a![class("anchor"), href("#routing"), "Routing"]],
        div![
            class("table-wrap"),
            table![
                thead![tr![th!["feature"], th!["status"], th!["notes"]]],
                tbody![
                    tr![
                        td![code!["page.rs"], ", nested ", code!["layout.rs"], ", ", code!["template.rs"]],
                        td!["✅"],
                        td!["unlimited nesting"],
                    ],
                    tr![
                        td![code!["page.html"], " (fragments and full documents)"],
                        td!["✅"],
                        td!["conflict with ", code!["page.rs"], " is an error or configurable precedence"],
                    ],
                    tr![
                        td!["dynamic, catch-all, optional catch-all segments"],
                        td!["✅"],
                        td!["typed ", code!["Path<T>"]],
                    ],
                    tr![td!["route groups, private folders"], td!["✅"], td![]],
                    tr![
                        td!["formal route ranking"],
                        td!["✅"],
                        td!["property-tested against a brute-force definition"],
                    ],
                    tr![td!["configurable/monorepo app directory, separate API directory"], td!["✅"], td![]],
                    tr![td!["conflict and naming diagnostics"], td!["✅"], td!["35 diagnostic codes"]],
                    tr![td!["symlink loops, Unicode, spaces"], td!["✅"], td![]],
                    tr![td!["parallel routes (", code!["@slot"], ", ", code!["default.rs"], ")"], td!["✅"], td![],],
                    tr![
                        td!["intercepting routes"],
                        td!["🟡"],
                        td!["page-level; not combined with slots; soft navigation only"],
                    ],
                    tr![td!["programmatic routes (", code!["App::get/route/ws"], ")"], td!["✅"], td![]],
                ],
            ],
        ],
        h2![id("rendering-data"), a![class("anchor"), href("#rendering-data"), "Rendering & data"]],
        div![
            class("table-wrap"),
            table![
                thead![tr![th!["feature"], th!["status"], th!["notes"]]],
                tbody![
                    tr![td!["SSR with typed extractors, ", code!["load"], " + ", code!["Data<T>"]], td!["✅"], td![],],
                    tr![td!["automatic static/dynamic inference"], td!["✅"], td!["reasons shown by the CLI"]],
                    tr![td!["SSG + ", code!["generate_params"], " + ", code!["DYNAMIC_PARAMS"]], td!["✅"], td![],],
                    tr![
                        td![
                            "ISR (",
                            code!["REVALIDATE"],
                            ", stale-while-revalidate, ",
                            code!["revalidate_path/tag"],
                            ")",
                        ],
                        td!["✅"],
                        td![],
                    ],
                    tr![
                        td!["streaming SSR (", code!["loading.rs"], ", ", code!["suspense"], ")"],
                        td!["✅"],
                        td!["out-of-order streaming, CSP nonces"],
                    ],
                    tr![
                        td![
                            code!["error.rs"],
                            ", ",
                            code!["global-error.rs"],
                            ", ",
                            code!["not-found.rs"],
                            ", redirects",
                        ],
                        td!["✅"],
                        td![],
                    ],
                    tr![td!["metadata merging, title templates, OG/Twitter"], td!["✅"], td![]],
                    tr![td![code!["sitemap.rs"], ", ", code!["robots.rs"]], td!["✅"], td![]],
                    tr![td!["generated Open Graph images"], td!["❌"], td!["use static files"]],
                    tr![
                        td!["parallel static generation (", code!["[build] concurrency"], ")"],
                        td!["❌"],
                        td!["pages render sequentially"],
                    ],
                ],
            ],
        ],
        h2![id("client"), a![class("anchor"), href("#client"), "Client"]],
        div![
            class("table-wrap"),
            table![
                thead![tr![th!["feature"], th!["status"], th!["notes"]]],
                tbody![
                    tr![td!["zero-JS pages by default"], td!["✅"], td!["runtime loaded only when needed"]],
                    tr![
                        td![code!["Link!"], " client navigation, prefetch, history API"],
                        td!["✅"],
                        td!["markup tested; browser behaviour not covered by automated browser tests"],
                    ],
                    tr![
                        td![code!["#[client]"], " islands with declarative behaviour"],
                        td!["🟡"],
                        td!["CSP-safe; limited operation set"],
                    ],
                    tr![td!["module islands (", code!["hydrate(element, props)"], ")"], td!["✅"], td![]],
                    tr![
                        td!["WASM client components"],
                        td!["🟡"],
                        td![
                            "protocol supports wasm-bindgen output; the build pipeline (",
                            code!["cargo build --target wasm32"],
                            " + ",
                            code!["wasm-bindgen"],
                            ") is manual",
                        ],
                    ],
                    tr![td!["Rust reactive DOM library / fine-grained signals in WASM"], td!["❌"], td![]],
                    tr![td![code!["#[server]"], " boundary"], td!["✅"], td!["compiled out on ", code!["wasm32"]],],
                ],
            ],
        ],
        h2![id("backend"), a![class("anchor"), href("#backend"), "Backend"]],
        div![
            class("table-wrap"),
            table![
                thead![tr![th!["feature"], th!["status"], th!["notes"]]],
                tbody![
                    tr![td![code!["route.rs"], " API routes, IntoResponse, JSON/text/bytes/streams"], td!["✅"], td![],],
                    tr![td!["middleware (global, root, nested)"], td!["✅"], td![]],
                    tr![
                        td!["cookies, sessions, CORS, rate limiting, request ids, CSRF"],
                        td!["✅"],
                        td!["rate limiting and memory sessions are per process"],
                    ],
                    tr![
                        td!["server actions + progressive forms + validation"],
                        td!["✅"],
                        td!["multipart unsupported"],
                    ],
                    tr![td!["SSE"], td!["✅"], td![]],
                    tr![
                        td!["WebSockets"],
                        td!["✅"],
                        td!["feature ", code!["websocket"], "; covered by compilation, not by an automated test",],
                    ],
                    tr![
                        td!["background/scheduled jobs, in-process queue"],
                        td!["🟡"],
                        td!["interval and daily UTC schedules; no cron expressions or persistent queue"],
                    ],
                    tr![td!["HTTP/1.1, HTTP/2 (h2c), keep-alive, gzip, graceful shutdown"], td!["✅"], td![]],
                    tr![td!["native TLS"], td!["❌"], td!["terminate at a proxy (see deployment)"]],
                    tr![td!["HTTP/3"], td!["❌"], td!["terminate at a proxy/CDN"]],
                    tr![td!["brotli compression"], td!["❌"], td!["gzip only"]],
                ],
            ],
        ],
        h2![id("assets"), a![class("anchor"), href("#assets"), "Assets"]],
        div![
            class("table-wrap"),
            table![
                thead![tr![th!["feature"], th!["status"], th!["notes"]]],
                tbody![
                    tr![td![code!["public/"], " with ETag, ranges, traversal protection"], td!["✅"], td![]],
                    tr![
                        td![
                            code!["global_css!"],
                            ", ",
                            code!["css_module!"],
                            " (scoping + minification at compile time)",
                        ],
                        td!["✅"],
                        td![],
                    ],
                    tr![td!["fingerprinted ", code!["asset!"], " with immutable caching"], td!["✅"], td![]],
                    tr![td![code!["Image!"], " markup (srcset, lazy, priority, dimensions)"], td!["✅"], td![]],
                    tr![td!["image resizing, WebP/AVIF conversion"], td!["❌"], td!["endpoint serves originals"],],
                    tr![td![code!["LocalFont"], " (", code!["@font-face"], ", preload)"], td!["✅"], td![]],
                    tr![
                        td!["JS minification / bundling"],
                        td!["❌"],
                        td!["the framework ships one hand-written runtime; no user JS bundler"],
                    ],
                    tr![td!["source maps"], td!["❌"], td!["not applicable without a bundler"]],
                ],
            ],
        ],
        h2![id("tooling"), a![class("anchor"), href("#tooling"), "Tooling"]],
        div![
            class("table-wrap"),
            table![
                thead![tr![th!["feature"], th!["status"], th!["notes"]]],
                tbody![
                    tr![
                        td![
                            code!["new"],
                            ", ",
                            code!["dev"],
                            ", ",
                            code!["build"],
                            ", ",
                            code!["start"],
                            ", ",
                            code!["check"],
                            ", ",
                            code!["routes"],
                            ", ",
                            code!["analyze"],
                            ", ",
                            code!["generate"],
                            ", ",
                            code!["doctor"],
                            ", ",
                            code!["docker"],
                            ", ",
                            code!["upgrade"],
                            ", ",
                            code!["clean"],
                        ],
                        td!["✅"],
                        td![],
                    ],
                    tr![
                        td!["update notice + ", code!["next-rust upgrade"], " from GitHub"],
                        td!["✅"],
                        td!["notifies once a day; never installs without the user running ", code!["upgrade"]],
                    ],
                    tr![
                        td!["dev: rebuild on change, keep serving on errors, browser overlay, live reload"],
                        td!["✅"],
                        td!["restarts the server process; no in-process hot-patching of Rust code"],
                    ],
                    tr![
                        td!["CSS-only hot swap without reload"],
                        td!["❌"],
                        td!["CSS is compiled into the binary, so changes rebuild and reload"],
                    ],
                    tr![td!["plugin traits (runtime + build)"], td!["🟡"], td!["minimal hook set, API may change"],],
                    tr![
                        td!["serverless adapter surface (", code!["App::handle"], ")"],
                        td!["🟡"],
                        td!["no packaged adapters for specific platforms"],
                    ],
                    tr![td!["edge (wasm32) runtime"], td!["❌"], td![]],
                    tr![
                        td!["Redis cache store"],
                        td!["❌"],
                        td!["implement ", code!["CacheStore"], " (example in docs)"],
                    ],
                ],
            ],
        ],
        h2![id("publishing"), a![class("anchor"), href("#publishing"), "Publishing"]],
        ul![
            li![
                "The crate names ",
                code!["next-rust"],
                ", ",
                code!["next-rust-core"],
                ", ",
                code!["next-rust-router"],
                ", ",
                code!["next-rust-view"],
                ", ",
                code!["next-rust-server"],
                ", ",
                code!["next-rust-macros"],
                ", ",
                code!["next-rust-build"],
                ", ",
                code!["next-rust-cache"],
                ", ",
                code!["next-rust-assets"],
                " and ",
                code!["next-rust-cli"],
                " were ",
                strong!["not taken on crates.io"],
                " when checked on 2026-09-17. Check again right before publishing.",
            ],
            li![
                code!["repository"],
                "/",
                code!["homepage"],
                " point to ",
                code!["github.com/iplustsolution/next-rust"],
                ".",
            ],
            li![
                "Publishing is automated by ",
                code![".github/workflows/release.yml"],
                " after CI passes on ",
                code!["main"],
                " (see CONTRIBUTING.md → Releasing). Publish order: assets → core → router → view → cache → server → macros → build → next-rust → cli.",
            ],
            li![
                code!["next-rust new"],
                " uses the crates.io version when it's published, and the GitHub repository otherwise (or with ",
                code!["--git"],
                ").",
            ],
        ],
        h2![id("roadmap-proposed"), a![class("anchor"), href("#roadmap-proposed"), "Roadmap (proposed)"]],
        ol![
            li![code!["next-rust build --wasm"], ": compile and bind WASM island crates automatically."],
            li!["Image optimizer behind an ", code!["image"], " feature (resize, WebP; AVIF optional)."],
            li!["Native TLS (rustls) behind a ", code!["tls"], " feature; HTTP/3 evaluation (quinn/h3)."],
            li!["Parallel static generation."],
            li!["Browser-level end-to-end tests for client navigation and islands."],
            li!["Redis ", code!["CacheStore"], "/", code!["SessionStore"], " in a companion crate."],
        ],
    ]
}
