#!/usr/bin/env python3
"""Regenerate crates/next-rust-view/src/tags.rs (one macro per HTML element)."""
import pathlib

NORMAL = """a abbr address article aside audio b blockquote body button canvas caption cite code colgroup datalist dd del details dfn dialog div dl dt em fieldset figcaption figure footer form h1 h2 h3 h4 h5 h6 head header hgroup html i iframe ins kbd label legend li main mark menu meter nav noscript object ol optgroup option output p picture pre progress q rp rt ruby s samp script section select slot small span strong style sub summary sup table tbody td template textarea tfoot th thead time title tr u ul var video svg g path circle rect ellipse polyline polygon defs symbol use_ clipPath linearGradient radialGradient stop""".split()
VOID = "area base br col embed hr img input link meta source track wbr".split()

out = ["//! Element macros. Generated by `scripts/gen_tags.py`; one macro per HTML element.",
       "//!",
       "//! Every macro accepts any mix of attributes ([`crate::attrs`]) and children",
       "//! (anything implementing [`crate::View`]), separated by commas.",
       ""]
for t in NORMAL:
    tag = t.rstrip('_')
    out.append(f"""/// `<{tag}>` element.
#[macro_export]
macro_rules! {t} {{
    ($($part:expr),* $(,)?) => {{ $crate::Element::new("{tag}")$(.with($part))* }};
}}
""")
for t in VOID:
    out.append(f"""/// `<{t}>` void element (children are ignored).
#[macro_export]
macro_rules! {t} {{
    ($($part:expr),* $(,)?) => {{ $crate::Element::new_void("{t}")$(.with($part))* }};
}}
""")
out.append("/// Names of all generated element macros.\npub const TAGS: &[&str] = &[" + ", ".join(f'"{t.rstrip("_")}"' for t in NORMAL + VOID) + "];\n")
out.append("/// Names of void elements.\npub const VOID_TAGS: &[&str] = &[" + ", ".join(f'"{t}"' for t in VOID) + "];\n")
target = pathlib.Path(__file__).resolve().parent.parent / "crates/next-rust-view/src/tags.rs"
target.write_text("\n".join(out))
